config/routes.rb
RealCrm::Application.routes.draw do

  get 'calendar_events', to: 'tasks#index'

  root to: 'main#index', as: 'home' 
    
  resources :accounts do  
    resources :user
    resources :deals
    resources :companies
    resources :contacts
    resources :tasks
    resources :histories 
    resources :conversations
    resources :messages
    get 'calendar' => 'calendar#index'
  end

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :users
  has_many :deals
  has_many :companies
  has_many :contacts
  has_many :tasks
  has_many :histories
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :account
  has_one :user, as: :owner
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :account
  has_one :user, as: :owner
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :account
  has_many :messages
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :account
  has_one :user, as: :owner
end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :account
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :conversation
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
  
  def permit?(controller, action)
    @controller = controller
    @action = action
    case title
      when 'admin'
        true
      when 'client'
        true
      when 'visiter'
       true
      else
        false
      end
      
  end
  
  private

    def request_to args={}
      not ( args[:controller].map(&:to_s) & [@controller] ).empty? and
      (not (args[:action].map(&:to_s)     & [@action]     ).empty? rescue true)
    end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :account
  has_one :user, as: :owner
  
  validates_presence_of :title
  
  def as_json(options = {})
    {
      id: self.id,
      title: self.title,
      description: self.description || "",
      start: starts_at.rfc822,
      end: ends_at.rfc822,
      allDay: self.all_day,
      recurring: false,
      url: Rails.application.routes.url_helpers.edit_account_task_path(self.account_id, id)
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role
  belongs_to :account
  has_many :deals
  has_many :companies
  has_many :tasks
  has_many :messages
  has_secure_password
  
  validates_associated :role
  
  def admin?
    role.title == 'admin'
  end
  
  def visiter?
    role.title == 'visiter'
  end
  
  def client?
    role.title == 'client'
  end
  
  def can?(controller, action)
    role.permit?(controller, action)
  end
 
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.where("sender_id = #{current_user.id}  or recipient_id = #{current_user.id}")
    @message = Message.new
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create

    @message = Message.new(message_params)
    @message.sender_id = current_user.id
    @message.status = 'new'
    @converse = Conversation.find_by(first_owner_id: @message.sender_id , second_owner_id: @message.recipient_id)
    @converse = Conversation.find_by(first_owner_id: @message.recipient_id , second_owner_id: @message.sender_id) if @converse.nil?
    @conversation = Conversation.new(account_id: current_user.account_id, first_owner_id: @message.sender_id, second_owner_id: @message.recipient_id) if @converse.nil?
    @conversation.save if @converse.nil?
    @message.conversation_id = @conversation.id if @converse.nil? else @message.conversation_id = @converse.id

    respond_to do |format|
      if @message.save
        format.html { redirect_to account_messages_path, notice: 'Message was successfully created.' }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:sender_id, :recipient_id, :title, :message, :status, :conversation_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def find_new_messages
    @new_messages = Message.where(recipient_id: current_user.id, status: 'new').count
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def normilize_event_date(start, ends, all_day)
    if start.utc == ends.utc or all_day
      "#{shortening_date start, all_day}"
    else
      "#{t '.between'} #{shortening_date start, all_day} #{t '.and'} #{shortening_date ends, all_day}"
    end
  end
  
  private
    
    def shortening_date(date, all_day)
      format = ""
      format += "%e#{t '.date_s'}"  unless date.strftime("%V%Y") == Date.today.strftime("%V%Y")
      format += " %A" unless date.strftime("%a %B") == Date.today.strftime("%a %B")
      format += " %B" unless date.strftime("%B") == Date.today.strftime("%B")
      format += " %Y" unless date.strftime("%Y") == Date.today.strftime("%Y")
      if all_day
        format += " #{t '.all_day'}"
      else
        format += " #{t '.today_at'}"  if date.strftime("%e %a %B %Y") == Date.today.strftime("%e %a %B %Y")
        unless date.strftime("%M").to_i == 0
          format += " %k:%M"
        else
          format += " %k #{t '.hours'}"
        end
      end
      date.strftime(format)
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/messages/_form.html.erb
<%= form_for @message , url: account_message_path(current_user.account_id, @message), remote: true do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <li class='new' id='message_content'>
    <%= f.label "Выберете собеседника" %>
    <%= f.collection_select :recipient_id, User.where("account_id = #{current_user.account_id} and id != #{current_user.id}"), :id, :email, {include_blank: false} %> <br/>
    <%= f.label "Ваше сообщение" %>
    <%= f.text_area :message %> <br/>
    <%= f.submit 'Отправить' %>
  </li>

<% end %>

app/views/messages/_message.html.erb
<% cache message do %>
<li class='new' id='message_<%= message.id %>'>
  <span class='field'>
    <% @sender = User.find_by(id: message.sender_id) %>
    <%= link_to @sender.email, account_user_path(current_user.account_id, message.sender_id) %>
    <%= message.title %>
    <%= auto_link(message.message) %>
    <%= message.created_at %>
  </span>
</li>

<li id='new_messages'></li>
</ul>

<% end %>

app/views/messages/create.js 2.erb
$("#new_message").replaceWith("<%=j render @message %>");

app/views/messages/create.js.erb
$("#new_messages").replaceWith("<%=j render @message %>");
$("#new_message")[0].reset();

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<ul>
<%= render @messages %>

<li id='new_message'></li>
</ul>

<%= link_to "add message", new_account_message_path(current_user.account), remote: true %>

app/views/messages/new.html.erb
<h1>Новый диалог</h1>

<%= render 'form' %>

app/views/messages/new.js.erb
$("<%=j render template: 'messages/new.html.erb' %>").appendTo("#new_message");

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender:</strong>
  <%= @message.sender_id %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @message.recipient_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @message.title %>
</p>

<p>
  <strong>Message:</strong>
  <%= @message.message %>
</p>

<p>
  <strong>Status:</strong>
  <%= @message.status %>
</p>