config/routes.rb
RealCrm::Application.routes.draw do

  get 'calendar_events', to: 'tasks#index'

  root to: 'main#index', as: 'home' 
    
  resources :accounts do  
    resources :user
    resources :deals
    resources :companies
    resources :contacts
    resources :tasks
    resources :histories 
    resources :conversations
    resources :messages
    get 'calendar' => 'calendar#index'
  end

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :users
  has_many :deals
  has_many :companies
  has_many :contacts
  has_many :tasks
  has_many :histories
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :account
  has_one :user, as: :owner
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :account
  has_one :user, as: :owner
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :account
  has_many :messages
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :account
  has_one :user, as: :owner
end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :account
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :conversation
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
  
  def permit?(controller, action)
    @controller = controller
    @action = action
    case title
      when 'admin'
        true
      when 'client'
        true
      when 'visiter'
       true
      else
        false
      end
      
  end
  
  private

    def request_to args={}
      not ( args[:controller].map(&:to_s) & [@controller] ).empty? and
      (not (args[:action].map(&:to_s)     & [@action]     ).empty? rescue true)
    end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :account
  has_one :user, as: :owner
  
  validates_presence_of :title
  
  def as_json(options = {})
    {
      id: self.id,
      title: self.title,
      description: self.description || "",
      start: starts_at.rfc822,
      end: ends_at.rfc822,
      allDay: self.all_day,
      recurring: false,
      url: Rails.application.routes.url_helpers.edit_account_task_path(self.account_id, id)
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role
  belongs_to :account
  has_many :deals
  has_many :companies
  has_many :tasks
  has_many :messages
  has_secure_password
  
  validates_associated :role
  
  def admin?
    role.title == 'admin'
  end
  
  def visiter?
    role.title == 'visiter'
  end
  
  def client?
    role.title == 'client'
  end
  
  def can?(controller, action)
    role.permit?(controller, action)
  end
 
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_special_params, only: [:show]
  after_action :history_note, only: [:create, :edit, :destroy]
  before_action :authorize

  # GET /tasks
  # GET /tasks.json
  def index
    respond_to do |format|
      format.html { 
        @tasks = Task.where(account_id: current_user.account_id)
      }
      format.json  {
        @tasks = Task.where(account_id: current_user.account_id)
        render json:  @tasks
      }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @task.starts_at = params[:date]
    @task.ends_at = params[:date]
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.account_id = current_user.account_id

    respond_to do |format|
      if @task.save
        format.html { redirect_to account_tasks_path(current_user.account_id), notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to account_tasks_path(current_user.account_id), notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { render nothing: true }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def set_special_params
      @owner = User.find_by(id: @task.responsible)
      @contact = Contact.find_by(id: @task.contact_id)
      @company = Company.find_by(id: @task.company_id)
      @deal = Deal.find_by(id: @task.deal_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :type_of_task, :description, :starts_at, :ends_at, :all_day, :responsible, :account_id, :contact_id, :company_id, :deal_id)
    end
    
    def history_note
      note = History.create(user_id: current_user.id, account_id: params[:account_id], action: "#{params[:action]} #{params[:controller]}", obj_name: "#{@task.title}", obj_link: account_deal_path(current_user.account_id, @task.id))
      note.save
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def find_new_messages
    @new_messages = Message.where(recipient_id: current_user.id, status: 'new').count
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def normilize_event_date(start, ends, all_day)
    if start.utc == ends.utc or all_day
      "#{shortening_date start, all_day}"
    else
      "#{t '.between'} #{shortening_date start, all_day} #{t '.and'} #{shortening_date ends, all_day}"
    end
  end
  
  private
    
    def shortening_date(date, all_day)
      format = ""
      format += "%e#{t '.date_s'}"  unless date.strftime("%V%Y") == Date.today.strftime("%V%Y")
      format += " %A" unless date.strftime("%a %B") == Date.today.strftime("%a %B")
      format += " %B" unless date.strftime("%B") == Date.today.strftime("%B")
      format += " %Y" unless date.strftime("%Y") == Date.today.strftime("%Y")
      if all_day
        format += " #{t '.all_day'}"
      else
        format += " #{t '.today_at'}"  if date.strftime("%e %a %B %Y") == Date.today.strftime("%e %a %B %Y")
        unless date.strftime("%M").to_i == 0
          format += " %k:%M"
        else
          format += " %k #{t '.hours'}"
        end
      end
      date.strftime(format)
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/tasks/_form.html.erb
<%= form_for @task , url: account_task_path(current_user.account_id, @task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Название" %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "Тип" %><br>
    <%= f.text_field :type_of_task %>
  </div>
  <div class="field">
    <%= f.label "Описание" %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label "Дата начала" %><br>
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="field">
    <%= f.label "Дата окончания" %><br>
    <%= f.datetime_select :ends_at %>
  </div>
  <div class="field">
    <%= f.label "Весь день" %><br>
    <%= f.check_box :all_day %>
  </div>
  <div class="field">
    <%= f.label "Ответственный" %><br>
    <%= f.collection_select :responsible, current_user.account.users, :id, :email, {include_blank: false} %>
  </div>
  <div class="field">
    <%= f.label "Контакт" %><br>
    <%= f.collection_select :contact_id, current_user.account.contacts, :id, :email, {include_blank: false} %>
  </div>
  <div class="field">
    <%= f.label "Компания" %><br>
    <%= f.collection_select :company_id, current_user.account.companies, :id, :email, {include_blank: false} %>
  </div>
  <div class="field">
    <%= f.label "Сделка" %><br>
    <%= f.collection_select :deal_id, current_user.account.deals, :id, :name, {include_blank: false} %>
  </div>
  <div class="actions">
    <%= f.submit "Сохранить" %>
  </div>
<% end %>

app/views/tasks/destroy.js.erb
$("#task_<%= @task.id %>").remove();

app/views/tasks/edit.html.erb
<h1>Редактирование задачи</h1>

<%= render 'form' %>

<%= link_to 'Отмена', account_tasks_path(current_user.account_id) %>

app/views/tasks/index.html.erb
<h1>Просмотр задач</h1>

<table>
  <thead>
    <tr>
      <th>Название</th>
      <th>Тип</th>
      <th>Описание</th>
      <th>Дата начала</th>
      <th>Дата окончания</th>
      <th>Весь день</th>
      <th>Ответственный</th>
      <th>Контакт</th>
      <th>Компания</th>
      <th>Сделка</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr id='task_<%= task.id %>'>
        <td><%= task.title %></td>
        <td><%= task.type_of_task %></td>
        <td><%= task.description %></td>
        <td><%= task.starts_at %></td>
        <td><%= task.ends_at %></td>
        <td><%= task.all_day %></td>
        <% @owner = User.find_by(id: task.responsible) %>
        <td><%= link_to @owner.email, account_user_path(task.account_id, task.responsible) %></td>
        <% @contact = Contact.find_by(id: task.contact_id) %>
        <td><%= link_to @contact.name, account_contact_path(task.account_id, task.contact_id) %></td>
        <% @company = Company.find_by(id: task.company_id) %>
        <td><%= link_to @company.name, account_company_path(task.account_id, task.company_id) %></td>
        <% @deal = Deal.find_by(id: task.deal_id) %>
        <td><%= link_to @deal.name, account_deal_path(task.account_id, task.deal_id) %></td>
        <td><%= link_to 'Подробнее', account_task_path(task.account_id, task) %></td>
        <td><%= link_to 'Редактировать', edit_account_task_path(task.account_id, task) %></td>
        <td><%= link_to 'Удалить', account_task_path(task.account_id, task), method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить задачу', new_account_task_path(current_user.account_id) %>

app/views/tasks/new.html.erb
<h1>Новая задача</h1>

<%= render 'form' %>

<%= link_to 'Отмена', account_tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Тип:</strong>
  <%= @task.type_of_task %>
</p>

<p>
  <strong>Описание:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Дата начала:</strong>
  <%= @task.starts_at %>
</p>

<p>
  <strong>Дата окончания:</strong>
  <%= @task.ends_at %>
</p>

<p>
  <strong>Весь день:</strong>
  <%= @task.all_day %>
</p>

<p>
  <strong>Ответственный:</strong>
  <%= @task.responsible %>
</p>

<p>
  <strong>Контакт:</strong>
  <%= @task.contact_id %>
</p>

<p>
  <strong>Компания:</strong>
  <%= @task.company_id %>
</p>

<p>
  <strong>Сделка:</strong>
  <%= @task.deal_id %>
</p>

<%= link_to 'Редактировать', edit_account_task_path(@task.account_id, @task) %> |
<%= link_to 'Назад', account_tasks_path %>