config/routes.rb
RealCrm::Application.routes.draw do

  get 'calendar_events', to: 'tasks#index'

  root to: 'main#index', as: 'home' 
    
  resources :accounts do  
    resources :user
    resources :deals
    resources :companies
    resources :contacts
    resources :tasks
    resources :histories 
    resources :conversations
    resources :messages
    get 'calendar' => 'calendar#index'
  end

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :users
  has_many :deals
  has_many :companies
  has_many :contacts
  has_many :tasks
  has_many :histories
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :account
  has_one :user, as: :owner
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :account
  has_one :user, as: :owner
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :account
  has_many :messages
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :account
  has_one :user, as: :owner
end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :account
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :conversation
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
  
  def permit?(controller, action)
    @controller = controller
    @action = action
    case title
      when 'admin'
        true
      when 'client'
        true
      when 'visiter'
       true
      else
        false
      end
      
  end
  
  private

    def request_to args={}
      not ( args[:controller].map(&:to_s) & [@controller] ).empty? and
      (not (args[:action].map(&:to_s)     & [@action]     ).empty? rescue true)
    end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :account
  has_one :user, as: :owner
  
  validates_presence_of :title
  
  def as_json(options = {})
    {
      id: self.id,
      title: self.title,
      description: self.description || "",
      start: starts_at.rfc822,
      end: ends_at.rfc822,
      allDay: self.all_day,
      recurring: false,
      url: Rails.application.routes.url_helpers.edit_account_task_path(self.account_id, id)
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role
  belongs_to :account
  has_many :deals
  has_many :companies
  has_many :tasks
  has_many :messages
  has_secure_password
  
  validates_associated :role
  
  def admin?
    role.title == 'admin'
  end
  
  def visiter?
    role.title == 'visiter'
  end
  
  def client?
    role.title == 'client'
  end
  
  def can?(controller, action)
    role.permit?(controller, action)
  end
 
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show, :edit, :update, :destroy]

  # GET /conversations
  # GET /conversations.json
  def index
    @conversations = Conversation.where(account_id: current_user.account_id)
  end

  # GET /conversations/1
  # GET /conversations/1.json
  def show
    if (@conversation.first_owner_id == current_user.id)
      @interlocutor = User.find_by(id: @conversation.second_owner_id)
    else
      @interlocutor = User.find_by(id: @conversation.first_owner_id)
    end
    @messages = Message.where(conversation_id: @conversation.id)
    @status_new = Message.where(conversation_id: @conversation.id, status: 'new', recipient_id: current_user.id)
    @status_new.each do |new_mes|
      new_mes.status = 'read'
      new_mes.save
    end
    @message = Message.new
    
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations
  # POST /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to @conversation, notice: 'Conversation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @conversation }
      else
        format.html { render action: 'new' }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1
  # PATCH/PUT /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1
  # DELETE /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conversation_params
      params.require(:conversation).permit(:first_owner_id, :second_owner_id, :account_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def normilize_event_date(start, ends, all_day)
    if start.utc == ends.utc or all_day
      "#{shortening_date start, all_day}"
    else
      "#{t '.between'} #{shortening_date start, all_day} #{t '.and'} #{shortening_date ends, all_day}"
    end
  end
  
  private
    
    def shortening_date(date, all_day)
      format = ""
      format += "%e#{t '.date_s'}"  unless date.strftime("%V%Y") == Date.today.strftime("%V%Y")
      format += " %A" unless date.strftime("%a %B") == Date.today.strftime("%a %B")
      format += " %B" unless date.strftime("%B") == Date.today.strftime("%B")
      format += " %Y" unless date.strftime("%Y") == Date.today.strftime("%Y")
      if all_day
        format += " #{t '.all_day'}"
      else
        format += " #{t '.today_at'}"  if date.strftime("%e %a %B %Y") == Date.today.strftime("%e %a %B %Y")
        unless date.strftime("%M").to_i == 0
          format += " %k:%M"
        else
          format += " %k #{t '.hours'}"
        end
      end
      date.strftime(format)
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/conversations/_form.html.erb
<%= form_for @message , url: account_message_path(current_user.account_id, @message), remote: true do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <li class='new' id='message_content'>
    <%= link_to @interlocutor.email, account_user_path(current_user.account, @interlocutor)%>
    <%= f.label "Введите Ваше сообщение" %>
    <%= f.text_area :message %>
    <%= f.submit 'Отправить' %>
  </li>

<% end %>

app/views/conversations/edit.html.erb
<h1>Editing conversation</h1>

<%= render 'form' %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<h1>Диалоги</h1>

    <% @conversations.each do |conversation| %>
    <div class='conversation'>
       
      <% if conversation.first_owner_id == current_user.id %>
        <% @owner = User.find_by(id: conversation.second_owner_id) %>
      <% else %>
        <% @owner = User.find_by(id: conversation.first_owner_id) %>
      <% end %>
      <%= link_to "Разговор с #{@owner.name}", account_conversation_path(current_user.account_id, conversation) %>
    </div>
    <%= link_to 'Удалить', account_conversation_path(current_user.account_id, conversation), id: 'delete', method: :delete, data: { confirm: 'Are you sure?' } %>
      <br>
    <% end %>
    <div class='clear'></div>
<%= link_to 'Создать новый диалог', new_account_message_path(current_user.account) %>

app/views/conversations/new.html.erb
<h1>New conversation</h1>

<%= render 'form' %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<p id="notice"><%= notice %></p>
<ul>
   <% @messages.each do |message| %>
      <li class='<%= message.status %>' id='message_<%= message.id %>'>
          <% @sender = User.find_by(id: message.sender_id) %>
          <%= link_to @sender.email, account_user_path(current_user.account_id, message.sender_id) %>
          <%= message.title %>
          <%= auto_link(message.message) %>
          <%= message.created_at %>
      </li>
    <% end %>

<li id='new_messages'></li>
</ul>

<%= render 'form' %>