config/routes.rb
RealCrm::Application.routes.draw do

  get 'calendar_events', to: 'tasks#index'

  root to: 'main#index', as: 'home' 
    
  resources :accounts do  
    resources :user
    resources :deals
    resources :companies
    resources :contacts
    resources :tasks
    resources :histories 
    resources :conversations
    resources :messages
    get 'calendar' => 'calendar#index'
  end

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :users
  has_many :deals
  has_many :companies
  has_many :contacts
  has_many :tasks
  has_many :histories
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :account
  has_one :user, as: :owner
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :account
  has_one :user, as: :owner
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :account
  has_many :messages
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :account
  has_one :user, as: :owner
end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :account
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :conversation
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
  
  def permit?(controller, action)
    @controller = controller
    @action = action
    case title
      when 'admin'
        true
      when 'client'
        true
      when 'visiter'
       true
      else
        false
      end
      
  end
  
  private

    def request_to args={}
      not ( args[:controller].map(&:to_s) & [@controller] ).empty? and
      (not (args[:action].map(&:to_s)     & [@action]     ).empty? rescue true)
    end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :account
  has_one :user, as: :owner
  
  validates_presence_of :title
  
  def as_json(options = {})
    {
      id: self.id,
      title: self.title,
      description: self.description || "",
      start: starts_at.rfc822,
      end: ends_at.rfc822,
      allDay: self.all_day,
      recurring: false,
      url: Rails.application.routes.url_helpers.edit_account_task_path(self.account_id, id)
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role
  belongs_to :account
  has_many :deals
  has_many :companies
  has_many :tasks
  has_many :messages
  has_secure_password
  
  validates_associated :role
  
  def admin?
    role.title == 'admin'
  end
  
  def visiter?
    role.title == 'visiter'
  end
  
  def client?
    role.title == 'client'
  end
  
  def can?(controller, action)
    role.permit?(controller, action)
  end
 
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :set_special_params, only: [:show]
  after_action :history_note, only: [:create, :edit, :destroy]
  before_action :authorize

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.where(account_id: current_user.account_id)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @owner   = User.find_by(id: @company.responsible)
    @contact = Contact.find_by(id: @company.contact_id)
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    @company.account_id = current_user.account_id

    respond_to do |format|
      if @company.save
        format.html { redirect_to account_company_path(current_user.account_id, @company), notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to account_companies_path(current_user.account_id), notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { render nothing: true }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    def set_special_params
      @owner   = User.find_by(id: @company.responsible)
      @contact = Contact.find_by(id: @company.contact_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :phone, :email, :site, :adress, :responsible, :account_id, :contact_id, :notes)
    end
    
    def history_note
      note = History.create(user_id: current_user.id, account_id: params[:account_id], action: "#{params[:action]} #{params[:controller]}", obj_name: "#{@company.name}", obj_link: account_deal_path(current_user.account_id, @company.id))
      note.save
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def find_new_messages
    @new_messages = Message.where(recipient_id: current_user.id, status: 'new').count
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def normilize_event_date(start, ends, all_day)
    if start.utc == ends.utc or all_day
      "#{shortening_date start, all_day}"
    else
      "#{t '.between'} #{shortening_date start, all_day} #{t '.and'} #{shortening_date ends, all_day}"
    end
  end
  
  private
    
    def shortening_date(date, all_day)
      format = ""
      format += "%e#{t '.date_s'}"  unless date.strftime("%V%Y") == Date.today.strftime("%V%Y")
      format += " %A" unless date.strftime("%a %B") == Date.today.strftime("%a %B")
      format += " %B" unless date.strftime("%B") == Date.today.strftime("%B")
      format += " %Y" unless date.strftime("%Y") == Date.today.strftime("%Y")
      if all_day
        format += " #{t '.all_day'}"
      else
        format += " #{t '.today_at'}"  if date.strftime("%e %a %B %Y") == Date.today.strftime("%e %a %B %Y")
        unless date.strftime("%M").to_i == 0
          format += " %k:%M"
        else
          format += " %k #{t '.hours'}"
        end
      end
      date.strftime(format)
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/companies/_form.html.erb
<%= form_for @company , url: account_company_path(current_user.account_id, @company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Название" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Телефон" %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :site %><br>
    <%= f.text_field :site %>
  </div>
  <div class="field">
    <%= f.label "Адрес" %><br>
    <%= f.text_area :adress %>
  </div>
  <div class="field">
    <%= f.label "Ответственный" %><br>
    <%= f.collection_select :responsible, current_user.account.users, :id, :email, {include_blank: false} %>
  </div>
  <div class="field">
    <%= f.label "Контакт" %><br>
    <%= f.collection_select :contact_id, current_user.account.contacts, :id, :email, {include_blank: false} %>
  </div>
  <div class="field">
    <%= f.label "Примечание" %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit "Сохранить"%>
  </div>
<% end %>

app/views/companies/destroy.js.erb
$("#company_<%= @company.id %>").remove();

app/views/companies/edit.html.erb
<h1>Редактирование компании</h1>

<%= render 'form' %>

<%= link_to 'Отмена', account_companies_path(current_user.account_id) %>

app/views/companies/index.html.erb
<h1>Просмотр компаний</h1>

<table>
  <thead>
    <tr>
      <th>Название</th>
      <th>Телефон</th>
      <th>Email</th>
      <th>Site</th>
      <th>Адрес</th>
      <th>Ответственный</th>
      <th>Контакт</th>
      <th>Примечание</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr id='company_<%= company.id %>'>
        <td><%= company.name %></td>
        <td><%= company.phone %></td>
        <td><%= company.email %></td>
        <td><%= company.site %></td>
        <td><%= company.adress %></td>
        <% @owner = User.find_by(id: company.responsible) %>
        <td><%= link_to @owner.email, account_user_path(company.account_id, company.responsible) %></td>
        <% @contact = Contact.find_by(id: company.contact_id) %>
        <td><%= link_to @contact.name, account_contact_path(company.account_id, company.contact_id) %></td>
        <td><%= company.notes %></td>
        <td><%= link_to 'Подробнее', account_company_path(current_user.account_id, company) %></td>
        <td><%= link_to 'Редактировать', edit_account_company_path(current_user.account_id, company) %></td>
        <td><%= link_to 'Удалить', account_company_path(current_user.account_id, company), method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить компанию', new_account_company_path %>

app/views/companies/new.html.erb
<h1>Новая компания</h1>

<%= render 'form' %>

<%= link_to 'Отмена', account_companies_path(current_user.account_id) %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Телефон:</strong>
  <%= @company.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @company.email %>
</p>

<p>
  <strong>Site:</strong>
  <%= @company.site %>
</p>

<p>
  <strong>Адрес:</strong>
  <%= @company.adress %>
</p>

<p>
  <strong>Ответственный:</strong>
  <%= link_to @owner.email, account_user_path(@company.account_id, @company.responsible) %>
</p>

<p>
  <strong>Контакт:</strong>
  <%= link_to @contact.name, account_contact_path(@company.account_id, @company.contact_id) %>
</p>

<p>
  <strong>Примечание:</strong>
  <%= @company.notes %>
</p>

<%= link_to 'Редактировать', edit_account_company_path(current_user.account_id, @company) %> |
<%= link_to 'Назад', account_companies_path(current_user.account_id) %>